### ISSUE TITLE
Website theme

### ISSUE THREAD

**Issue by CloneWith** [offfc/offfc.github.io#1]
For consistent and novel experience, we can design a simple theme for our website:

- [x] Color scheme (main colour can be osu! pink or ⑨ light blue)
- [x] Logo (by Art team)
- [x] Font (can consider, optional)
- [x] Mainpage visual design
- *More to add here*

**Comment by NaughtyChas** [comment]
> * [ ]  Font (can consider, optional)

See #5

**Comment by NaughtyChas** [comment]
> * [ ]  Logo (by Art team)

New logo design has already being used in #4 . Remember to have a look at this checkbox if that PR gets merged, or there is some other logo or static assets mentioned in this one?
