### ISSUE TITLE
Staff name changes

### ISSUE THREAD

**Issue by NaughtyChas** [offfc/offfc.github.io#47]
![image](https://github.com/user-attachments/assets/49229f77-8c9c-4f98-9bcc-692949e520a8)

Bruh just changed into `[SHK] Arcadia`

**Comment by CloneWith** [comment]
wonderful intel PENTIUM

**Comment by NaughtyChas** [comment]
Farewell our beloved **My Angel Kuroe**...
...who just came back with his new ID **[SHK]MAKuroe**.

Already updated to pr, will be merged soon.

**Comment by CloneWith** [comment]
Whatsoever we'll remember his great name: **My Angel Juroe (ver. 有错字受)**
